package com.makers.makersbnb.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;

@RestController
public class StaticPageController {
    // Home page
    @GetMapping("/")
    public ModelAndView welcome() {
        ModelAndView modelAndView = new ModelAndView("/LandingPage");
        // for now, imagine this value was generated by querying the database
        Integer nSpaces = 100;
        // this next line makes nSpaces available in the template
        modelAndView.addObject("nSpaces", nSpaces);
        return modelAndView;
    }

    @GetMapping("/contactus")
    public String contactPage() {
        return "info@makersbnb.com";
    }

    @GetMapping("/termsandconditions")
    public String termsConditionsPage() {
        return "Coming soon! In the meantime, please behave yourselves.";
    }
}
